apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello-client
  name: hello-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-client
  template:
    metadata:
      labels:
        app: hello-client
    spec:
      containers:
      - image: hello-client-image:latest
        imagePullPolicy: Never
        name: hello-client-pod
