apiVersion: v1
kind: Service
metadata:
  name: hello-server
  labels:
    name: hello-server
spec:
  ports:
  - protocol: TCP
    port: 55555
    targetPort: 55555
  type: NodePort
  selector:
    app: hello-server
