apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello-server
  name: hello-server
spec:
  replicas: 10
  selector:
    matchLabels:
      app: hello-server
  template:
    metadata:
      labels:
        app: hello-server
    spec:
      containers:
      - image: hello-server-image:latest # Local minikube image.
        imagePullPolicy: Never
        name: hello-server-pod
        ports:
        - containerPort: 55555 # GRPC port
        resources:
          ## Want to limit the number of CPU the pods can use as 
          ## to not kill the computer.
          limits:
            cpu: "0.1"
#          requests:
#            cpu: "0.1"

---
apiVersion: v1
kind: Service
metadata:
  name: hello-service
  labels:
    name: hello-server
spec:
  ports:
  - protocol: TCP
    port: 80
    targetPort: 55555
  type: NodePort
  selector:
    app: hello-server
